---
  build: pdf
  lang: zh
  license: ccbyncnd30
  config: latex/config.yml
  template: latex/template.tex
  preface-files: chp0*.md
  chapter-files: chp{1,2,3,4,5,6,7,8,9,10,101,102,103,104,105,106,107}-*.md
  jeykll: true
  
